## rectangular 1

test_that("rotatePots 01: rotate N_pots N places to result in the same location, generateLayout1", {
  pL_1 <- PTR_load_dummy_data(3)
  pL_2 <- PTR_rotatePots(pL_1,pL_1$board_1$input$pots)
  expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[1]])
  expect_equal(pL_1$board_1$points$Label_[[2]],pL_2$board_1$points$Label_[[2]])
  expect_equal(pL_1$board_2$points$Label_[[3]],pL_2$board_2$points$Label_[[3]])
  expect_equal(pL_1$board_2$points$Label_[[4]],pL_2$board_2$points$Label_[[4]])
  expect_equal(pL_1$board_3$points$Label_[[5]],pL_2$board_3$points$Label_[[5]])
  expect_equal(pL_1$board_3$points$Label_[[6]],pL_2$board_3$points$Label_[[6]])
})
test_that("rotatePots 02: rotate N_pots N places to result in the same location, generateLayout2 > rectangular 1", {
    pL_1 <- PTR_load_dummy_data(5)
    pL_2 <- PTR_rotatePots(pL_1,dim(pL_1$board_1$points)[[1]])
    expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[1]])
    expect_equal(pL_1$board_1$points$Label_[[15]],pL_2$board_1$points$Label_[[15]])
    expect_equal(pL_1$board_2$points$Label_[[2]],pL_2$board_2$points$Label_[[1]])
    expect_equal(pL_1$board_2$points$Label_[[1]],pL_2$board_2$points$Label_[[2]])
})

test_that("rotatePots 03: rotate 2>1 via positive numbers, generateLayout1", {
  pL_1 <- PTR_load_dummy_data(4)
  pots_shifted_down <- PTR_rotatePots(pL_1)
  expect_equal(pL_1$board_1$points$Label_[[1]],pots_shifted_down$board_1$points$Label_[[17]])
  expect_equal(pL_1$board_1$points$Label_[[2]],pots_shifted_down$board_1$points$Label_[[18]])
  expect_equal(pL_1$board_1$points$Label_[[17]],pots_shifted_down$board_1$points$Label_[[15]])
  expect_equal(pL_1$board_1$points$Label_[[18]],pots_shifted_down$board_1$points$Label_[[16]])
})
test_that("rotatePots 04: rotate 1>2 via negative numbers, generateLayout1", {
  pL_1 <- PTR_load_dummy_data(4)
  pL_2 <- PTR_rotatePots(pL_1,-2)
  expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[3]])
  expect_equal(pL_1$board_1$points$Label_[[2]],pL_2$board_1$points$Label_[[4]])
  expect_equal(pL_1$board_1$points$Label_[[17]],pL_2$board_1$points$Label_[[1]])
  expect_equal(pL_1$board_1$points$Label_[[18]],pL_2$board_1$points$Label_[[2]])
})
# test_that("rotatePots 05: rotate N_pots N places to result in the same location, generateLayout1", {
#   pL_1 <- PTR_load_dummy_data(4)
#   pL_2 <- PTR_rotatePots(pL_1,pL_1$board_1$input$pots)
#   expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[1]])
#   expect_equal(pL_1$board_1$points$Label_[[17]],pL_2$board_1$points$Label_[[17]])
#   expect_equal(pL_1$board_2$points$Label_[[8]],pL_2$board_2$points$Label_[[8]])
#   expect_equal(pL_1$board_2$points$Label_[[1]],pL_2$board_2$points$Label_[[1]])
# })
# test_that("rotatePots 06: rotate 2>1 via positive numbers, generateLayout1", {
#   pL_1 <- PTR_load_dummy_data(5)
#   pots_shifted_down <- PTR_rotatePots(pL_1)
#   expect_equal(pL_1$board_1$points$Label_[[1]],pots_shifted_down$board_1$points$Label_[[17]])
#   expect_equal(pL_1$board_1$points$Label_[[2]],pots_shifted_down$board_1$points$Label_[[18]])
#   expect_equal(pL_1$board_1$points$Label_[[17]],pots_shifted_down$board_1$points$Label_[[15]])
#   expect_equal(pL_1$board_1$points$Label_[[18]],pots_shifted_down$board_1$points$Label_[[16]])
# })
# test_that("rotatePots 07: rotate 1>2 via negative numbers, generateLayout1", {
#   pL_1 <- PTR_load_dummy_data(4)
#   pL_2 <- PTR_rotatePots(pL_1,-2)
#   expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[3]])
#   expect_equal(pL_1$board_1$points$Label_[[2]],pL_2$board_1$points$Label_[[4]])
#   expect_equal(pL_1$board_1$points$Label_[[17]],pL_2$board_1$points$Label_[[1]])
#   expect_equal(pL_1$board_1$points$Label_[[18]],pL_2$board_1$points$Label_[[2]])
# })
# test_that("rotatePots 08: rotate N_pots N places to result in the same location, generateLayout1", {
#   pL_1 <- PTR_load_dummy_data(4)
#   pL_2 <- PTR_rotatePots(pL_1,pL_1$board_1$input$pots)
#   expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[1]])
#   expect_equal(pL_1$board_1$points$Label_[[17]],pL_2$board_1$points$Label_[[17]])
#   expect_equal(pL_1$board_2$points$Label_[[8]],pL_2$board_2$points$Label_[[8]])
#   expect_equal(pL_1$board_2$points$Label_[[1]],pL_2$board_2$points$Label_[[1]])
# })
# test_that("rotatePots 09: rotate N_pots N places to result in the same location, generateLayout1", {
#   pL_1 <- PTR_load_dummy_data(4)
#   pL_2 <- PTR_rotatePots(pL_1,pL_1$board_1$input$pots)
#   expect_equal(pL_1$board_1$points$Label_[[1]],pL_2$board_1$points$Label_[[1]])
#   expect_equal(pL_1$board_1$points$Label_[[17]],pL_2$board_1$points$Label_[[17]])
#   expect_equal(pL_1$board_2$points$Label_[[8]],pL_2$board_2$points$Label_[[8]])
#   expect_equal(pL_1$board_2$points$Label_[[1]],pL_2$board_2$points$Label_[[1]])
# })
