#' @importFrom stringr str_c
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 annotate
#' @importFrom ggplot2 theme_minimal
#' @importFrom ggplot2 ggplot_build
#' @importFrom ggplot2 aes
#' @importFrom ggforce geom_circle
#' @importFrom here here
#' @importFrom stats na.omit
