#' Generate a dummy BoardLayout as generated by `PTR_generateBoardLayouts` by feeding a set of dummy-data to it
#' This function is mostly supposed to be used for testing purposes, and should not be normally called.
#' @param set Select a dummy testset and return the results of `PTR_generateBoardLayouts`. As a rule, higher values for 'set' become more calculation-intense
#' @return Layouts as defined by `PTR_generateBoardLayouts`
#' @export
#' @importFrom stringr str_c
#'
#' @examples layout2 <- PTR_test_call(2)
PTR_test_call <- function(set = 1) {
    if (set == 1) {
        print("pots: 40, width: 20, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 40, board_width = 20, board_height = 20, radius = 5, distance = 0))
    } else if (set == 2) {
        print("pots: 43, width: 20, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 43, board_width = 20, board_height = 20, radius = 5, distance = 0))
    } else if (set == 3) {
        print("pots: 60, width: 30, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 60, board_width = 30, board_height = 20, radius = 5, distance = 0))
    } else if (set == 4) {
        print("pots: 64, width: 30, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 64, board_width = 30, board_height = 20, radius = 5, distance = 0))
    } else {
        stop(simpleError(str_c("Please define an integer between 1-4")))
    }
}
