#' Generate a dummy BoardLayout as generated by `PTR_generateBoardLayouts` by feeding a set of dummy-data to it
#' This function is mostly supposed to be used for testing purposes, and should not be normally called.
#' @param set Select a dummy testset and return the results
#' of `PTR_generateBoardLayouts`/`PTR_generateBoardLayouts2`.
#' As a rule, higher values for 'set' become more calculation-intense
#' Sets 1-3 leverage `PTR_generateBoardLayouts`
#' Sets 4-5 leverage `PTR_generateBoardLayouts2`
#'
#' @return Layouts as defined by `PTR_generateBoardLayouts`
#' @export
#' @importFrom stringr str_c
#' @examples
#' layout2 <- PTR_test_call(2)
PTR_test_call <- function(set = 1) {
    if (set == 1) {
        print("pots: 40, width: 20, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 40, board_width = 20, board_height = 20, radius = 5, distance = 0))
    } else if (set == 2) {
        print("pots: 43, width: 20, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 43, board_width = 20, board_height = 20, radius = 5, distance = 0))
    } else if (set == 3) {
        print("pots: 60, width: 30, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 60, board_width = 30, board_height = 20, radius = 5, distance = 0))
    } else if (set == 4) {
        # Example usage for rectangular pots
        print("pots = 17,board_width = 30,board_height = 60,pot_rectangle_width = 12,pot_rectangle_height = 10,distance = 0,pot_type = rectangle")
        return(PTR_generateBoardLayouts2(
            pots = 17,
            board_width = 30,
            board_height = 60,
            pot_rectangle_width = 12,
            pot_rectangle_height = 10,
            distance = 0,
            lbls = paste0("rectangle_", 1:17),
            pot_type = "rectangle"
        ))
    } else if (set == 5) {
        # Example usage for rectangular pots
        print("pots = 64,board_width = 30,board_height = 60,pot_radius = 5,distance = 0,pot_type = circle")
        return(PTR_generateBoardLayouts2(
            pots = 64,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            distance = 0,
            lbls = paste0("circle_", 1:64),
            pot_type = "circle"
        ))
    } else if (set == 6) {

        # Example usage for square pots
        return(PTR_generateBoardLayouts2(
            pots = 64,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            pot_diameter = 5 * 2,
            pot_rectangle_width = 5 * 2,
            pot_rectangle_height = 5 * 2,
            distance = 0,
            lbls = paste0("square_", 1:64),
            pot_type = "square"
        ))
    } else if (set == 5) {
        print("pots: 64, width: 30, height: 20, radius: 5")
        return(PTR_generateBoardLayouts(pots = 64, board_width = 30, board_height = 20, radius = 5, distance = 0))
    } else {
        stop(simpleError(str_c("Please define an integer between 1-4")))
    }
}
#' # Example usage for rectangular pots
#' layouts_rect <- PTR_generateBoardLayouts2(
#' pots = 17,
#' board_width = 30,
#' board_height = 60,
#' pot_rectangle_width = 12,
#' pot_rectangle_height = 10,
#' distance = 0,
#' lbls = paste0("rectangle_", 1:17),
#' pot_type = "rectangle"
#' )
#' layouts_rect
#' # Example usage for circular pots
#' layouts_circle <- PTR_generateBoardLayouts2(
#' pots = 64,
#' board_width = 30,
#' board_height = 60,
#' pot_radius = 5,
#' distance = 0,
#' lbls = paste0("circle_", 1:64),
#' pot_type = "circle"
#' )
#' layouts_circle
#' # Example usage for square pots
#' layouts_square <- PTR_generateBoardLayouts2(
#' pots = 64,
#' board_width = 30,
#' board_height = 60,
#' pot_radius = 5,
#' pot_diameter = 5 * 2,
#' pot_rectangle_width = 5 * 2,
#' pot_rectangle_height = 5 * 2,
#' distance = distance,
#' lbls = paste0("square_", 1:64),
#' pot_type = "square"
#' )
#' layouts_square
