#' pads an integer to length by prepending zeros
#'
#' @param number - an integer to pad
#' @param length_to_pad_to
#'
#' @return a padded number
#' @noRd
#' @keywords internal
#' @importFrom stringr str_c
#'
#' @examples num_new <- pad_to_length(1,3)
pad_to_length <- function(number, length_to_pad_to) {
    if (isFALSE(is.integer(as.integer(number)))) {
        swarning <- simpleWarning(str_c("<number> is not of type <integer>. This might be okay, but be aware"))
        warning(swarning)
    }
    cond <- str_length(number) < length_to_pad_to
        number[cond] <- str_c("0", number[cond])
    return(number)
}
#'
#'
#' @importFrom utils askYesNo
#' @noRd
#' @keywords internal
#' @importFrom stringr str_c
#'
warn_iterations <- function(it) {
    askYesNo(str_c("The number of required iterations is above ", it, ". This might take some time, so you might want to consider different restraints. Do you want to continue with current inputs?"))
}
#' Title
#'
#' @param boards
#'
#' @return all labels in consecutive order.
#' @export
#' @keywords internal
#'
collect_labels <- function(boards) {
    ret <- c()
    for (board in boards) {
        ret <- append(ret, board$input$lbls)
    }
    return(ret)
}
#' Generate a dummy BoardLayout as generated by `PTR_generateBoardLayouts` by feeding a set of dummy-data to it
#' This function is mostly supposed to be used for testing purposes, and should not be normally called.
#' @param set Select a dummy testset and return the results
#' of `PTR_generateBoardLayouts`/`PTR_generateBoardLayouts2`.
#' As a rule, higher values for 'set' become more calculation-intense
#' Sets 1-3 leverage `PTR_generateBoardLayouts`
#' Sets 4-5 leverage `PTR_generateBoardLayouts2`
#'
#' @return Layouts as defined by `PTR_generateBoardLayouts`
#' @export
#' @importFrom stringr str_c
#' @examples
#' layout2 <- PTR_load_dummy_data(2)
PTR_load_dummy_data <- function(set = 0) {
        explanations <- c("pots: 40, width: 20, height: 20, pot_radius: 5"
        ,"pots: 43, width: 20, height: 20, pot_radius: 5"
        ,"pots: 60, width: 30, height: 20, pot_radius: 5"
        ,"pots: 32, width: 30, height: 60, pot_radius: 5, lbls: UU/UG/ABAU/ABAG"
        ,"pots: 17, width: 30, height: 60, pot_rectangle_width: 12, pot_rectangle_height: 10, pot_type: rectangle"
        ,"pots: 64, width: 30, height: 60, pot_radius: 5, pot_type: circle"
        ,"pots: 64, width: 30, height: 60, pot_radius: 5, pot_rectangle_width: 10, pot_rectangle_height: 10, pot_type: rectangle"
        ,"pots: 32, width: 30, height: 60, pot_radius: 5, lbls: UU/UG/ABAU/ABAG, pot_type: square")
    if (set != 0) {
        print(explanations[[set]])
    }
    if (set == 0) { ## print overview on indeces
        print(str_c("Select a test-set by supplying an integer between '1' and '",length(explanations),"':"))
        print(explanations)
    } else if (set == 1) {
        return(PTR_generateBoardLayouts(pots = 40, board_width = 20, board_height = 20, pot_radius = 5, distance = 0))
    } else if (set == 2) {
        return(PTR_generateBoardLayouts(pots = 43, board_width = 20, board_height = 20, pot_radius = 5, distance = 0))
    } else if (set == 3) {
        return(PTR_generateBoardLayouts(pots = 60, board_width = 30, board_height = 20, pot_radius = 5, distance = 0))
    } else if (set == 4) {
        # Example usage for declaring custom labels.
        #
        N <- 8
        labels <- c("UU","UG","ABAU","ABAG")
        repeated_vector <- rep(labels, each = N)

        # Create the indices vector
        indices <- rep(1:N, times = length(labels))

        # Combine repeated_vector and indices using paste
        result <- paste(repeated_vector, indices, sep = "_")
        return(PTR_generateBoardLayouts(
            pots = 32,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            distance = 0,
            lbls = result))
    } else if (set == 5) {
        # Example usage for rectangular pots
        return(PTR_generateBoardLayouts2(
            pots = 17,
            board_width = 30,
            board_height = 60,
            pot_rectangle_width = 12,
            pot_rectangle_height = 10,
            distance = 0,
            lbls = paste0("rectangle_", 1:17),
            pot_type = "rectangle"
        ))
    } else if (set == 6) {
        # Example usage for rectangular pots
        return(PTR_generateBoardLayouts2(
            pots = 64,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            distance = 0,
            lbls = paste0("circle_", 1:64),
            pot_type = "circle"
        ))
    } else if (set == 7) {
        # Example usage for square pots
        return(PTR_generateBoardLayouts2(
            pots = 64,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            pot_diameter = 5 * 2,
            pot_rectangle_width = 5 * 2,
            pot_rectangle_height = 5 * 2,
            distance = 0,
            lbls = paste0("square_", 1:64),
            pot_type = "square"
        ))
    } else if (set == 8) {
        # Example usage for declaring custom labels.
        #
        N <- 8
        labels <- c("UU","UG","ABAU","ABAG")
        repeated_vector <- rep(labels, each = N)

        # Create the indices vector
        indices <- rep(1:N, times = length(labels))

        # Combine repeated_vector and indices using paste
        result <- paste(repeated_vector, indices, sep = "_")
        # Example usage for square pots
        return(PTR_generateBoardLayouts2(
            pots = 32,
            board_width = 30,
            board_height = 60,
            pot_radius = 5,
            pot_diameter = 5 * 2,
            pot_rectangle_width = 5 * 2,
            pot_rectangle_height = 5 * 2,
            distance = 0,
            lbls = result,
            pot_type = "square"
        ))
    } else {
        stop(simpleError(str_c("Please define an integer between 0-8")))
    }
}
